AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: {{cookiecutter.project_name.lower().replace(' ', '-')}} serverless application

Globals:

  Function:
    Timeout: 30
    Runtime: python3.8
    Tracing: Active

Resources:

  ServiceFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./src
      Handler: service.app.lambda_handler
      FunctionName: 'lambda-service'
      Description: 'Lambda service' 

